export const SET_CONVERSATIONS = '@@SLACK/SET_CONVERSATIONS';
export const SET_MEMBERS = '@@SLACK/SET_MEMBERS';
export const ADD_MESSAGE = '@@SLACK/ADD_MESSAGE';
export const STARTUP_ERROR = '@@SLACK/STARTUP_ERROR';
export const SELECT_CONVERSATION = '@@SLACK/SELECT_CONVERSATION';
export const SEND_MESSAGE = '@@SLACK/SEND_MESSAGE';
export const UPDATE = '@@SLACK/UPDATE';